### ISSUE TITLE
Broken textures/icons

### ISSUE THREAD

**Issue by DTech10** [ThinkingStudios/Litematica-Forge#35]
MaFgLib-0.1.7-mc1.19.2
Forgematica-0.1.6-mc1.19.2

<details>
<summary>Screenshots</summary>

![2023-11-02_13 26 59](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/bbd53cb5-8d95-4c68-83bf-b675ebb3fbdf)
![2023-11-02_13 27 04](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/a2dee884-59a3-43da-bd5e-849cd1aa52f9)
![2023-11-02_13 27 05](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/1771f280-26e3-4073-99e7-5b05c3cd03a7)
![2023-11-02_13 27 11](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/285d2a81-7899-476d-9bf6-5702f5001463)
![2023-11-02_13 27 13](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/5819b32b-036e-408f-b182-94b481971a9a)
![2023-11-02_13 27 17](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/2a273e0a-aad4-4f41-85eb-ab3acc2fe244)
![2023-11-02_13 27 22](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/a82f206a-7f46-41d1-9566-1a4cf2f6ca50)
![2023-11-02_13 27 25](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/87023c87-078d-44c0-9d15-940ef017e754)
![2023-11-02_13 27 27](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/ef411500-82e5-4b04-8fff-d88751014ee7)
![2023-11-02_13 27 37](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/51c72cf6-7c3e-482d-a159-a84ec71bbcc7)
![2023-11-02_13 27 49](https://github.com/ThinkingStudios/Litematica-Forge/assets/136813833/7b8479f3-2e1a-4ca4-ac63-55f120ad1862)
</details>

**Comment by ForgeLoverAndUser** [comment]
ive got the same issue bro

**Comment by ForgeLoverAndUser** [comment]
is there somewhere in Forgematica that has a Load or error log? or maybe check Minecraft's logs?

**Comment by DTech10** [comment]
This is the [Latest Log](https://mclo.gs/9Aqlb06)

<details>
<summary>I found this</summary>

`[29Dec2023 11:36:18.235] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: forgematica:textures/gui/gui_widgets.pngjava.io.FileNotFoundException: forgematica:textures/gui/gui_widgets.png`
```
	at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.m_118155_(SimpleTexture.java:83) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6335_(SimpleTexture.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6704_(SimpleTexture.java:29) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:94) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_157179_(RenderSystem.java:1216) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_157456_(RenderSystem.java:1209) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at fi.dy.masa.malilib.render.RenderUtils.bindTexture(RenderUtils.java:79) ~[MaFgLib-0.1.7-mc1.19.2.jar%23472!/:0.1.7-mc1.19.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.bindTexture(WidgetBase.java:157) ~[MaFgLib-0.1.7-mc1.19.2.jar%23472!/:0.1.7-mc1.19.2]
	at fi.dy.masa.malilib.gui.button.ButtonGeneric.render(ButtonGeneric.java:120) ~[MaFgLib-0.1.7-mc1.19.2.jar%23472!/:0.1.7-mc1.19.2]
	at fi.dy.masa.malilib.gui.GuiBase.drawButtons(GuiBase.java:557) ~[MaFgLib-0.1.7-mc1.19.2.jar%23472!/:0.1.7-mc1.19.2]
	at fi.dy.masa.malilib.gui.GuiBase.m_6305_(GuiBase.java:170) ~[MaFgLib-0.1.7-mc1.19.2.jar%23472!/:0.1.7-mc1.19.2]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.3.0-universal.jar%23556!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.3.0-universal.jar%23556!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23551!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

</details>

**Comment by TexBlock** [comment]
This has been fixed in the version just released.
