### ISSUE TITLE
Not compatible with Mekanism mod

### ISSUE THREAD

**Issue by LitingERS** [ThinkingStudios/Litematica-Forge#48]
when I place something about tube(all kinds),and quantum entangloporter _(blocks about logistics)_ ,litematica-forge can save it,but if I load it,the game will crash
[crashreport.zip](https://github.com/ThinkingStudios/Litematica-Forge/files/14357383/crashreport.zip)
<img width="960" alt="crashimage" src="https://github.com/ThinkingStudios/Litematica-Forge/assets/86134152/ba30cae6-c37a-4931-9699-070a78154c2b">
the picture shows some blocks that can cause the crash
the zip is the crash report

**Comment by Vadym-beep** [comment]
I have the same problem.
I saw this in my logs:
`[29/03/2024 12:11:44 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[29/03/2024 12:11:44 PM] ---------------------------------------------------------------------------------------
[29/03/2024 12:11:44 PM] 
[29/03/2024 12:11:44 PM] -- Head --
[29/03/2024 12:11:44 PM] Thread: Render thread
[29/03/2024 12:11:44 PM] Suspected Mods: 
[29/03/2024 12:11:44 PM] 	Mekanism (mekanism), Version: 10.4.5
[29/03/2024 12:11:44 PM] 		Issue tracker URL: https://github.com/mekanism/Mekanism/issues
[29/03/2024 12:11:44 PM] 		at TRANSFORMER/mekanism@10.4.5/mekanism.common.network.BasePacketHandler.sendToAllTracking(BasePacketHandler.java:210)
[29/03/2024 12:11:44 PM] 
[29/03/2024 12:11:44 PM] 	MaFgLib (mafglib), Version: 0.1.8-mc1.20.1
[29/03/2024 12:11:44 PM] 		at TRANSFORMER/mafglib@0.1.8-mc1.20.1/fi.dy.masa.malilib.event.TickHandler.onClientTick(TickHandler.java:36)
[29/03/2024 12:11:44 PM] 
[29/03/2024 12:11:44 PM] 	Forgematica (forgematica), Version: 0.1.3-mc1.20.1
[29/03/2024 12:11:44 PM] 		at TRANSFORMER/forgematica@0.1.3-mc1.20.1/fi.dy.masa.litematica.world.ChunkSchematic.m_6978_(ChunkSchematic.java:98)
[29/03/2024 12:11:44 PM] Stacktrace:
[29/03/2024 12:11:44 PM] 	at net.minecraftforge.network.PacketDistributor.lambda$trackingChunk$9(PacketDistributor.java:241) ~[forge-1.20.1-47.2.20-universal.jar%23513!/:?] {re:classloading}`

When a schematic contains any kind of Mekanism block (even ores) and I load the schematic, the game crashes.

**Comment by templeofshadow** [comment]
Having the same issue with a big custom modpack. Here is my crash report:
[crash-2024-04-19_08.18.14-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/15041043/crash-2024-04-19_08.18.14-client.txt)

**Comment by TexBlock** [comment]
![image](https://github.com/ThinkingStudios/Litematica-Forge/assets/65154269/19fe6871-a50a-4026-8103-c8f655f7a6ef)

i will upload new version fix this bug

**Comment by TexBlock** [comment]
uploaded new version

**Comment by sudoBash418** [comment]
This issue seems to have reappeared between 0.1.6 and 0.1.7.

[crash-2024-11-10_13.47.45-server.txt](https://github.com/user-attachments/files/17693044/crash-2024-11-10_13.47.45-server.txt)
