### ISSUE TITLE
0.1.0-mc1.20.4 NeoForge - Critical injection failure: Callback method renderSlotHighlights

### ISSUE THREAD

**Issue by jade-clarke** [ThinkingStudios/Litematica-Forge#51]
MC Version: 1.20.4
NF Version: NeoForge 20.4.196
---
Steps to reproduce:

1. Fresh install of Minecraft 1.20.4
2. Install NeoForge
3. Add the following to the mods folder:
  - MaFgLib-0.1.4-mc1.20.4.jar
  - Forgematica-0.1.0-mc1.20.4.jar
4. Launch Minecraft
---
Crashlog:
```
MultiMC version: 0.7.0-3837


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.35, 13.107.246.35, 2620:1ec:bdf::35, 2620:1ec:46::35]

textures.minecraft.net resolves to:
    [13.107.213.35, 13.107.246.35, 2620:1ec:bdf::35, 2620:1ec:46::35]

api.mojang.com resolves to:
    [13.107.213.35, 13.107.246.35, 2620:1ec:46::35, 2620:1ec:bdf::35]


Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.20.41/.minecraft


Java path is:
/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/bin/java


Checking Java version...
Java is version 21.0.2, using 32-bit architecture, from Eclipse Adoptium.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.20.41/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-macos-arm64.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  /Applications/MultiMC.app/Data/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/fancymodloader/earlydisplay/2.0.17/earlydisplay-2.0.17.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/fancymodloader/loader/2.0.17/loader-2.0.17.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/coremods/6.0.4/coremods-6.0.4.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/fancymodloader/spi/2.0.17/spi-2.0.17.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/securejarhandler/2.1.24/securejarhandler-2.1.24.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/accesstransformers/at-modlauncher/10.0.1/at-modlauncher-10.0.1.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/accesstransformers/10.0.1/accesstransformers-10.0.1.jar
  /Applications/MultiMC.app/Data/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/mergetool/2.0.0/mergetool-2.0.0-api.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/bus/7.2.0/bus-7.2.0.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/JarJarSelector/0.4.0/JarJarSelector-0.4.0.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/JarJarMetadata/0.4.0/JarJarMetadata-0.4.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.13.0+mixin.0.8.5/sponge-mixin-0.13.0+mixin.0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/org/jetbrains/annotations/22.0.0/annotations-22.0.0.jar
  /Applications/MultiMC.app/Data/libraries/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/srgutils/0.4.15/srgutils-0.4.15.jar
  /Applications/MultiMC.app/Data/libraries/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
  /Applications/MultiMC.app/Data/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /Applications/MultiMC.app/Data/libraries/com/machinezoo/noexception/noexception/1.7.1/noexception-1.7.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
  /Applications/MultiMC.app/Data/libraries/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
  /Applications/MultiMC.app/Data/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  /Applications/MultiMC.app/Data/libraries/net/neoforged/JarJarFileSystems/0.4.0/JarJarFileSystems-0.4.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Mods:
  [✔️] Forgematica-0.1.0-mc1.20.4.jar
  [✔️] MaFgLib-0.1.4-mc1.20.4.jar

Params:
  --username Username --version 1.20.4 --gameDir /Applications/MultiMC.app/Data/instances/1.20.41/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 12 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --fml.neoForgeVersion 20.4.196 --fml.fmlVersion 2.0.17 --fml.mcVersion 1.20.4 --fml.neoFormVersion 20231207.154220 --launchTarget forgeclient

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.20.4 - NeoForge", -XstartOnFirstThread, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 36552


Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
[32m[23:31:03.680] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Username, --version, 1.20.4, --gameDir, /Applications/MultiMC.app/Data/instances/1.20.41/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --assetIndex, 12, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --fml.neoForgeVersion, 20.4.196, --fml.fmlVersion, 2.0.17, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 20231207.154220, --launchTarget, forgeclient, --width, 854, --height, 480] 
[m[32m[23:31:03.683] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.2 by Eclipse Adoptium; OS Mac OS X arch aarch64 version 14.3.1 
[m[32m[23:31:03.741] [main/INFO] [loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow 
[m[32m[23:31:03.840] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 
[m[32m[23:31:03.874] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.5 
[m[32m[23:31:03.887] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.4 
[m[32m[23:31:03.895] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.3 
[m[32m[23:31:03.903] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.2 
[m[32m[23:31:03.911] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1 
[m[32m[23:31:03.925] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.1 got version 4.1 
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[m[32m[23:31:03.995] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.13.0+mixin.0.8.5/sponge-mixin-0.13.0+mixin.0.8.5.jar%23158!/ Service=ModLauncher Env=CLIENT 
[m[32m[23:31:04.092] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Forgematica-0.1.0-mc1.20.4.jar" of type MOD with provider {mods folder locator at /Applications/MultiMC.app/Data/instances/1.20.41/.minecraft/mods} 
[m[32m[23:31:04.092] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "MaFgLib-0.1.4-mc1.20.4.jar" of type MOD with provider {mods folder locator at /Applications/MultiMC.app/Data/instances/1.20.41/.minecraft/mods} 
[m[32m[23:31:04.149] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Apple M1 Pro GL version 4.1 Metal - 88, Apple 
[m[32m[23:31:04.226] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "client-1.20.4-20231207.154220-srg.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@71870da7 
[m[32m[23:31:04.226] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-20.4.196-universal.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@71870da7 
[m[32m[23:31:04.277] [main/INFO] [loading.moddiscovery.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection 
[m[32m[23:31:04.277] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "ForgedNetworkingAPI-0.1.0-mc1.20.4.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5a67e962 
[m[32m[23:31:04.278] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-neoforge-0.3.5.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@5a67e962 
[m[32m[23:31:04.731] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 
[m[32m[23:31:04.736] [main/INFO] [LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.4, --gameDir, /Applications/MultiMC.app/Data/instances/1.20.41/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --uuid, <PROFILE ID>, --username, Username, --assetIndex, 12, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 854, --height, 480] 
[m[32m[23:31:04.959] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). 
[m2024-03-11 23:31:05,095 main WARN Advanced terminal features are not available in this environment
[23:31:07] [Datafixer Bootstrap/INFO] [mojang/DataFixerBuilder]: 198 Datafixer optimizations took 68 milliseconds
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
Exiting with -1
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:175)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:175)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at TRANSFORMER/minecraft@1.20.4/net.minecraft.client.main.Main.main(Main.java:216)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderSlotHighlights(Lnet/minecraft/client/gui/GuiGraphics;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in forgematica.mixins.json:MixinHandledScreen from mod forgematica failed injection check, (0/1) succeeded. Scanned 1 target(s). No refMap loaded.
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 53 more
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
```

**Comment by TexBlock** [comment]
fixed in 0.1.1
